#ifndef SAMPLE_VERSION_H
#define SAMPLE_VERSION_H

#define VER_FILEVERSION 1,0,0,0
#define VER_FILEVERSION_STR "1.0.0.0"
#define VER_PRODUCTVERSION VER_FILEVERSION
#define VER_PRODUCTVERSION_STR VER_FILEVERSION_STR

#define VER_COMPANYNAME ""
#define VER_FILEDESCRIPTION ""

#endif
