#ifndef SAMPLE_VERSION_H
#define SAMPLE_VERSION_H

#define VER_FILEVERSION 1024,0,0,1204
#define VER_FILEVERSION_STR "1024.0.0.1204"
#define VER_PRODUCTVERSION VER_FILEVERSION
#define VER_PRODUCTVERSION_STR VER_FILEVERSION_STR

#endif
